# Generated by Django 5.2.8 on 2026-02-21 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_dek_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dek_auth_tag',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dek_iv',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='encrypted_dek',
        ),
    ]
