# Generated by Django 5.1.3 on 2026-03-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_encrypted_private_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='kek_salt',
            field=models.BinaryField(blank=True, default=b''),
        ),
    ]
