# Generated by Django 5.2.8 on 2026-02-20 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('encrypted_data', models.BinaryField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EncryptedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('record_type', models.CharField(choices=[('json', 'JSON'), ('text', 'Text')], max_length=10)),
                ('encrypted_data', models.BinaryField()),
                ('keywords_json', models.TextField(default='[]')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_type', models.CharField(max_length=20)),
                ('logic_mode', models.CharField(max_length=3)),
                ('token_count', models.IntegerField(default=0)),
                ('result_count', models.IntegerField(default=0)),
                ('duration_ms', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=128)),
                ('token_type', models.CharField(choices=[('K', 'Keyword'), ('N', 'N-gram'), ('B', 'Bigram')], default='K', max_length=1)),
                ('score', models.FloatField(default=0.0)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='drive.encryptedfile')),
            ],
            options={
                'indexes': [models.Index(fields=['token'], name='drive_filei_token_e8f53c_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecordIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=128)),
                ('token_type', models.CharField(choices=[('K', 'Keyword'), ('N', 'N-gram'), ('B', 'Bigram')], default='K', max_length=1)),
                ('score', models.FloatField(default=0.0)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='drive.encryptedrecord')),
            ],
            options={
                'indexes': [models.Index(fields=['token'], name='drive_recor_token_a9354e_idx')],
            },
        ),
    ]
