# Generated by Django 5.1.3 on 2026-03-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drive', '0002_encryptedfile_encrypted_file_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptedfile',
            name='encrypted_dek',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='encryptedfile',
            name='iv_aes',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='encryptedfile',
            name='kek_iv',
            field=models.BinaryField(default=b''),
        ),
        migrations.AddField(
            model_name='encryptedfile',
            name='nonce_cc',
            field=models.BinaryField(default=b''),
        ),
    ]
